name: Create macOS Release

on:
    push:
        branches:
            - release

env:
    RELEASE_VERSION: v0.1.10
    RELEASE_NOTES: "Actual first release"


jobs:
    release:
        runs-on: macos-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Install Rust
              run: |
                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
                export PATH="$HOME/.cargo/bin:$PATH"
                rustup update
            - name: Build and package
              run: |
                cargo build --release
                tar czf graphust.tar.gz target/release/graphust
            - name: Create release and attach binary
              uses: softprops/action-gh-release@v1
              with:
                tag_name: ${{ env.RELEASE_VERSION }}
                files: graphust.tar.gz
            - name: Update GIT tag
              run: |
                git config --global user.email "noreply@example.com"
                git config --global user.name "${{ github.actor }}"
                git tag ${{ env.RELEASE_VERSION }}
                git push origin ${{ env.RELEASE_VERSION }}
            - name: Print SHA
              run: shasum -a 256 graphust.tar.gz | awk '{print $1}'
