name: Create macOS Release

on:
    push:
        branches:
            - release

env:
    RELEASE_VERSION: v0.1.3
    RELEASE_NOTES: "Actual first release"


jobs:
    release:
        runs-on: macos-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Install Rust
              run: |
                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
                export PATH="$HOME/.cargo/bin:$PATH"
                rustup update
            - name: Build and package
              run: |
                cargo build --release
                tar czf graphust.tar.gz target/release/graphust
            - name: Upload Binary
              uses: actions/upload-artifact@v3
              with:
                name: graphust
                path: graphust.tar.gz
            - name: Update GIT tag
              run: |
                git config --global user.email "noreply@example.com"
                git config --global user.name "${{ github.actor }}"
                git tag ${{ env.RELEASE_VERSION }}
                git push origin ${{ env.RELEASE_VERSION }}
            - name: Create Release
              uses: actions/create-release@v1
              with:
                tag_name: ${{ env.RELEASE_VERSION }}
                release_name: Release ${{ env.RELEASE_VERSION }}
                body: ${{ env.RELEASE_NOTES }}
                draft: false
                prerelease: false
            - name: Attach Artifact to Release
              uses: actions/upload-release-asset@v1
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: graphust.tar.gz
                asset_name: graphust.tar.gz
                asset_content_type: application/gzip
            - name: Print SHA
              run: shasum -a 256 graphust.tar.gz | awk '{print $1}'
